language: node_js
node_js:
- '0.10'
deploy:
  provider: openshift
  user: davethompson21@gmail.com
  password:
    secure: Y+yUSAaAknxBlGMuXeIk9H5F0URZTfmyItUuF3LaKY+CObustm0tsSR4D+52xRhDx/fdnOkVviLHEbJI8qIYAFJzNIDLisjcB1lFKYZFtkscp+gO8+v++s1L3tldstzzo7v2euK9WVYdsqB5G0e9thfqRkXkrRszaoaqMmdgUiTTlmzl3s/afcyoHVoLV58CDcVt2ZrAIommxGoEOocmuoBGeEQwPmrQDauE7aRRfzNXbt9eFcY/xc81L3Gk3aqjAgyyQgoeWpUK1k2lc0Rt8e2FmP7MEvLdsgiPvKSU821tnD2EqwCDLHGXKXJDSvfMAQKH0R6zLLkHu380PZv9GuqvrHhqZ+8XShzMlhQT4DEuPHMXiYZrOOY1BN+DQAlUe7Onb4ahFakbdJt2Is099QKQoRDdvonIKgp7/a6c29kzLMh7X7hwy+gjMJkie2SSZnqDgbFnRVgGVCQjU4MzTmX2NZI4qSPkA9AyaskL58IdMSIK0mXmaMRhpmAFYQ2vbcp7yovBQkY1Z4XQdBJs/CIsS3Cg3fm1g7/IUd/LFiW0nK0BUoLrmm260wTHcmdd+yD9mbcYTz3Mt7ovPaH7HPEFaz+4XWYgxNq87rTdoceo+nuJrTxFda9PYDKqrfoRMucHUQL1QkSDe/IyVASGxwT89y7vtl0JXUqYxbwDXlQ=
  app: expressjsseed
  domain: davet1985
  on:
    repo: davet1985/expressjs-seed
    branch: openshift
